Repository siderolabs/pkgs, pull requests merged in 2020-07, with the labels that each got.

#136 feat: upgrade containerd to v1.3.6
  containerd/pkg.yaml
Labels: status/approved

#138 feat: upgrade Linux to v5.7.7
  kernel/config-amd64
  kernel/pkg.yaml
Labels: status/approved, status/lgtm

#139 feat: upgrade runc to v1.0.0-rc91
  runc/pkg.yaml
Labels: status/approved

#140 feat: downgrade runc to v1.0.0-rc90
  runc/pkg.yaml
Labels: status/approved, status/lgtm

#141 feat: update Go to 1.14.5
  Pkgfile
Labels: status/approved, status/lgtm

#142 feat: support for multi-arch image amd64/arm64
  .drone.yml
  Makefile
  Pkgfile
  kernel/config-arm64
  open-isns/pkg.yaml
Labels: status/approved, status/lgtm

#143 feat: add grub
  Makefile
  grub/pkg.yaml
Labels: status/approved, status/lgtm

#144 chore: update deps.png
  deps.png
Labels: status/approved, status/lgtm

#145 feat: add FUSE kernel support
  .drone.yml
  kernel/config-amd64
Labels: status/lgtm
