Repository siderolabs/pkgs, pull requests merged in 2021-12, with the labels that each got.

#363 feat: update CNI to 1.0.1, separate package for flannel
  Makefile
  ca-certificates/pkg.yaml
  cni/pkg.yaml
  flannel-cni/pkg.yaml
Labels: status/approved

#364 feat: update Linux to 5.15.6
  kernel/kernel-prepare/pkg.yaml
  kernel/kernel/config-amd64
  kernel/kernel/config-arm64
Labels: status/ok-to-test

#365 feat: update Go to 1.17.4
  Pkgfile
Labels: status/ok-to-test

#366 feat: enable additional support for RPi hardware
  kernel/kernel/config-arm64
Labels: status/ok-to-test

#367 feat: update runc to 1.0.3
  runc/pkg.yaml
Labels: status/ok-to-test

#368 feat: update tools to 0.9.0
  Pkgfile
Labels: status/ok-to-test

#369 feat: update Go to 1.17.5
  Pkgfile
Labels: status/ok-to-test

#370 feat: update Go to 1.17.5
  Pkgfile
Labels: status/ok-to-test

#371 feat: update iPXE to the latest available version
  ipxe/patches/bigint.patch
  ipxe/patches/eeprom.patch
  ipxe/pkg.yaml
Labels: status/ok-to-test

#372 feat: provide build instructions for NVIDIA kernel module
  .drone.yml
  Makefile
  containerd/pkg.yaml
  kernel/build/certs/x509.genkey
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/build/pkg.yaml
  kernel/build/scripts/filter-hardened-check.py
  kernel/kernel/pkg.yaml
  kernel/prepare/patches/hardening.kconfig.patch
  kernel/prepare/patches/sign-file.patch
  kernel/prepare/pkg.yaml
  nonfree/kmod-nvidia/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#373 feat: update Linux to 5.15.11
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/prepare/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#375 fix: kexec on rpi4
  u-boot/pkg.yaml
  u-boot/rockpi4/patches/sram.patch
Labels: status/ok-to-test, status/ok-to-merge

#374 feat: (kernel) enable amdgpu
  kernel/build/config-amd64
Labels: status/ok-to-test, status/ok-to-merge

#376 chore: fix `=m` kernel build options
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge
