Repository siderolabs/pkgs, pull requests merged in 2024-04, with the labels that each got.

#929 fix: xz vulnerability
  Pkgfile
  liblzma/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility

#930 fix: revert musl to 1.2.4
  Pkgfile
  musl/patches/elf.h-add-typedefs.patch
  musl/patches/handle-aux-at-base.patch
  musl/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#932 feat: Go 1.22.2, Linux 6.6.24
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/build/patches/btf_ids.patch
  kernel/build/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#933 backport: feat: go 1.22.2, Linux 6.6.24
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/build/patches/btf_ids.patch
  kernel/build/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#934 feat: enable zboot on arm64 with zstd compression
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#935 feat: enable BFQ IO scheduler
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-merge

#937 feat: update Linux 6.6.26, containerd 1.7.15
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#940 fix: use proper EFI zBoot image
  kernel/kernel/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#942 feat: update Linux to 6.6.28
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#943 backport: feat: update Linux to 6.6.28
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#944 feat(intel): add support for power management and ACPI options for Intel CPUs
  kernel/build/config-amd64
Labels: status/ok-to-merge

#945 feat: enable SELinux
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/build/scripts/filter-hardened-check.py
Labels: status/ok-to-test, status/ok-to-merge

#946 feat: compress amd64 Linux kernel using zstd
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#947 feat: update containerd to 1.7.16
  Pkgfile
Labels: status/ok-to-test, status/ok-to-merge

#949 feat: update Linux to 6.6.29
  .github/workflows/ci.yaml
  .github/workflows/weekly.yaml
  Makefile
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#950 backports: for v1.7.1
  .github/workflows/ci.yaml
  .github/workflows/weekly.yaml
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge
