Repository siderolabs/pkgs, pull requests merged in 2024-09, with the labels that each got.

#1020 feat: update runc to 1.1.14
  Pkgfile
Labels: status/ok-to-test, status/ok-to-merge

#1021 feat: bump releases
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
  runc/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1022 feat: update Go 1.22.7, other bumps
  Pkgfile
Labels: status/ok-to-test, status/ok-to-merge

#1024 chore: drop UBSAN patch
  kernel/build/patches/0001-bpf-Replace-bpf_lpm_trie_key-0-length-array-with-flexible-array.patch 
  kernel/build/patches/README.md
Labels: status/ok-to-test, status/ok-to-merge

#1025 fix: add mpt3sas UBSAN patches
  kernel/build/patches/README.md
  kernel/build/patches/mpt3sas-ubsan.patch
Labels: status/ok-to-test, status/ok-to-merge

#1026 feat: update Linux to 6.6.51
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1029 feat: enable INET_DIAG
  kernel/build/config-amd64
  kernel/build/config-arm64
  kernel/build/scripts/filter-hardened-check.py
Labels: status/ok-to-merge

#1030 feat: update Linux firmware to 20240909
  Pkgfile
Labels: status/ok-to-test, status/ok-to-merge

#1032 feat: update Linux to 6.6.52
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1034 fix: lvm2 modprobe path
  lvm2/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1035 fix: lvm2 modprobe path
  lvm2/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1036 feat: enable transparent huge pages in madvise mode
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1019 feat: update xfsprogs 6.10.1
  Makefile
  Pkgfile
  libattr/pkg.yaml
  xfsprogs/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1039 feat: add libselinux, libsepol, pcre2 and libcap
  .github/renovate.json
  .kres.yaml
  Makefile
  Pkgfile
  libcap2/pkg.yaml
  libselinux/patches/musl-lstat.patch
  libselinux/patches/selabel-digest-uninit.patch
  libselinux/pkg.yaml
  libsepol/pkg.yaml
  pcre2/pkg.yaml
  reproducibility/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility
