Repository siderolabs/pkgs, pull requests merged in 2025-01, with the labels that each got.

#1133 chore: drop unused cert copy
  kernel/kernel/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1132 fix: Kernel missing I2C_MUX support and si2168 driver as result of it
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-merge

#1134 Update config-arm64 to add Rasperry Pi watchdog support
  kernel/build/config-arm64
Labels: status/ok-to-merge

#1135 feat: update Linux to 6.12.8
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1136 fix: adjust kernel options around ACPI/PCI/EFI
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1137 feat: update Linux to 6.12.9
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1138 feat: update containerd to v2.0.2
  Pkgfile
  containerd/patches/cni-deadlock.patch
  containerd/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1140 feat: update Go to 1.23.5
  Pkgfile
Labels: status/ok-to-test, status/ok-to-merge

#1141 chore: rekres to fix reproducibility build
  .github/renovate.json
  Makefile
Labels: status/ok-to-test, status/ok-to-merge, integration/reproducibility

#1142 feat: update Linux to 6.2.10
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge

#1143 feat: bump dependencies
  Pkgfile
  ca-certificates/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1144 fix: certificates CA
  ca-certificates/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1146 fix: build CNI plugins statically linked
  cni/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#1147 feat: update Linux to 6.12.11
  Pkgfile
  kernel/build/config-amd64
  kernel/build/config-arm64
Labels: status/ok-to-test, status/ok-to-merge
